### ISSUE TITLE
English as default language (in Android)

### ISSUE THREAD

**Issue by matsobdev** [covid19cz/erouska-homepage#78]
I suggest to make english a default language in app, czech an other one. If non-czech user opens app, has it in czech right now. If english would be a default one it would be english right of the bat and still czech for natives.

**Comment by davidvavra** [comment]
Hi, we discussed this a lot internally and the final decision was that this is an app only for Czech Republic (for now) and that's why primary language should be Czech. Concern is primarily with Slovak and Ukrainian minorities - they want the app in Czech more than in English. And these minorities are larger than others (Spanish speaking for example). Workaround for Spanish speakers is to set English as secondary language in Android settings. Then they will have app in English, not in Czech. Or help us translate the app to Spanish, anyone can translate here: https://covid19cz.oneskyapp.com/
